apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts
  labels:
    {{- include "contacts.labels" . | nindent 4}}
    app.kubernetes.io/component: contacts
spec:
  replicas: {{ .Values.contacts.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: contacts
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: contacts
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: contacts
          image: {{ .Values.contacts.image }}
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: contacts_db_url
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 1
            httpGet:
              path: /
              port: 3000
